"""The Python interfaces are a projection of the LinkML schema, not a copy of it.

`slarti/domain.py` is generated by `gen-pydantic` (`make domain`). If the schema and
the committed projection disagree, the implementation is typed against a model nobody
validates — so the drift is a test failure, exactly like `slarti docs --check`.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from slarti import findings, registry
from slarti.domain import Constraint, Enforcer, Finding, Severity

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = "model/schema/slarti.yaml"  # relative: gen-pydantic records the path it was given
GENERATED = ROOT / "slarti" / "domain.py"


@pytest.mark.skipif(shutil.which("gen-pydantic") is None, reason="linkml is not installed")
def test_generated_interfaces_match_the_schema() -> None:
    result = subprocess.run(
        ["gen-pydantic", SCHEMA], cwd=ROOT, capture_output=True, text=True, check=True
    )
    assert result.stdout == GENERATED.read_text(encoding="utf-8"), (
        "slarti/domain.py is stale — run `make domain`."
    )


def test_the_schema_rejects_an_enforcer_kind_it_does_not_define() -> None:
    with pytest.raises(registry.RegistryError):
        registry.load_enforcer({"kind": "vibes"})


def test_a_report_serialises_to_the_shape_the_schema_declares() -> None:
    report = findings.Report(checked=1)
    report.add(
        Finding(
            id="OWN-1",
            severity=Severity.error,
            file="model/schema/slarti.yaml",
            subject="Task",
            message="class 'Task' has no owner.",
            remedy="Add an owner annotation.",
        )
    )
    payload = report.as_schema()
    assert payload.summary.errors == 1
    assert payload.findings is not None
    assert payload.findings[0].severity == "error"


def test_a_constraint_carries_its_enforcer_even_when_nothing_enforces_it() -> None:
    constraint = Constraint(id="U1", statement="Humans review it.", enforced_by=Enforcer())
    assert registry.is_unenforced(constraint.enforced_by)
    assert registry.kind_text(constraint.enforced_by) == "none"
