from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

CONFIG = """# slarti: paths only. Settings belong to the tools that own them.
[paths]
arch = "docs/models/arch"
schema = "docs/models/schema"
shapes = "docs/models/shapes"
constraints = "docs/models/constraints.yaml"
data_valid = "docs/models/data/valid"
data_invalid = "docs/models/data/invalid"
document = "docs/architecture.md"
diagrams = "docs/diagrams"
build = "build"
"""

ARCH = """specification {
  element system
  element container
}

model {
  example = system 'Example' {
    api = container 'API' {
      metadata {
        owns 'Thing'
      }
    }
  }
}

views {
  view index {
    title 'Landscape'
    include *
  }
}
"""

SCHEMA = """id: https://example.org/example
name: example
prefixes:
  example: https://example.org/example/
  linkml: https://w3id.org/linkml/
default_prefix: example
default_range: string
imports:
  - linkml:types

classes:
  Thing:
    annotations:
      owner: example.api
    description: An example entity, owned by the API container.
    attributes:
      id:
        identifier: true
"""

CONSTRAINTS = """# The join table between prose and enforcement.
constraints: []
"""

DOCUMENT = """# Architecture

## Context

<!-- slarti:begin diagram:index -->
<!-- slarti:end diagram:index -->

## Ownership

<!-- slarti:begin ownership -->
<!-- slarti:end ownership -->

## Constraints

<!-- slarti:begin constraints -->
<!-- slarti:end constraints -->

## Unverified invariants

<!-- slarti:begin unverified -->
<!-- slarti:end unverified -->
"""

AGENTS = """# Agent contract for this repository

## Files you may edit

- `docs/models/arch/*.c4` — LikeC4 sources
- `docs/models/schema/*.yaml` — LinkML schema
- `docs/models/shapes/*.ttl` — hand-written SHACL
- `docs/models/constraints.yaml` — the rule registry
- `docs/models/data/valid/*`, `docs/models/data/invalid/*` — fixtures
- prose outside generated regions in `docs/architecture.md`

## Files you must never edit

- anything under `docs/diagrams/`
- anything between `<!-- slarti:begin ... -->` and `<!-- slarti:end ... -->`

Those regions are regenerated by `slarti docs`; edits there are reported as DOC-2.

## Loop

1. Edit model sources.
2. Run `slarti check --json`.
3. Every finding carries a rule ID, a file and a remedy. Apply the remedy.
4. Run `slarti docs` before committing; `slarti docs --check` gates the merge.
5. `slarti report --json` describes every rule, shape and check ID, with remedies.

Every rule stated in the prose belongs in `docs/models/constraints.yaml`, either with an
enforcer or as `enforced_by: none` with a reason. Unenforced is honest; unstated is not.
"""

WORKFLOW = """name: architecture

on: [push, pull_request]

jobs:
  slarti:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: npm ci
      - run: pip install uv && uv tool install slarti
      - run: slarti doctor
      - run: slarti check
      - run: slarti docs --check
"""


@dataclass(frozen=True)
class Scaffolded:
    """Files written by init, and files left alone because they existed."""

    written: list[str]
    skipped: list[str]


FILES: dict[str, str] = {
    "slarti.toml": CONFIG,
    "AGENTS.md": AGENTS,
    "docs/models/arch/example.c4": ARCH,
    "docs/models/schema/example.yaml": SCHEMA,
    "docs/models/constraints.yaml": CONSTRAINTS,
    "docs/architecture.md": DOCUMENT,
    ".github/workflows/architecture.yml": WORKFLOW,
}

DIRECTORIES = (
    "docs/models/shapes",
    "docs/models/data/valid",
    "docs/models/data/invalid",
    "docs/diagrams",
)


def init(root: Path) -> Scaffolded:
    """Scaffold the conventional layout. Refuses to overwrite anything (I1)."""
    written, skipped = [], []
    for name in DIRECTORIES:
        (root / name).mkdir(parents=True, exist_ok=True)
    for name, body in sorted(FILES.items()):
        target = root / name
        if target.exists():
            skipped.append(name)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        written.append(name)
    return Scaffolded(written=written, skipped=skipped)
